/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RailRouteImport } from './routes/rail'
import { Route as RoadRouteImport } from './routes/road'
import { Route as SkyRouteImport } from './routes/sky'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as WaterRouteImport } from './routes/water'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RailRoute = RailRouteImport.update({
  id: '/rail',
  path: '/rail',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadRoute = RoadRouteImport.update({
  id: '/road',
  path: '/road',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyRoute = SkyRouteImport.update({
  id: '/sky',
  path: '/sky',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterRoute = WaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rail': typeof RailRoute
  '/road': typeof RoadRoute
  '/sky': typeof SkyRoute
  '/stays': typeof StaysRoute
  '/water': typeof WaterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rail': typeof RailRoute
  '/road': typeof RoadRoute
  '/sky': typeof SkyRoute
  '/stays': typeof StaysRoute
  '/water': typeof WaterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rail': typeof RailRoute
  '/road': typeof RoadRoute
  '/sky': typeof SkyRoute
  '/stays': typeof StaysRoute
  '/water': typeof WaterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rail' | '/road' | '/sky' | '/stays' | '/water'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rail' | '/road' | '/sky' | '/stays' | '/water'
  id: '__root__' | '/' | '/rail' | '/road' | '/sky' | '/stays' | '/water'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RailRoute: typeof RailRoute
  RoadRoute: typeof RoadRoute
  SkyRoute: typeof SkyRoute
  StaysRoute: typeof StaysRoute
  WaterRoute: typeof WaterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rail': {
      id: '/rail'
      path: '/rail'
      fullPath: '/rail'
      preLoaderRoute: typeof RailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/road': {
      id: '/road'
      path: '/road'
      fullPath: '/road'
      preLoaderRoute: typeof RoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sky': {
      id: '/sky'
      path: '/sky'
      fullPath: '/sky'
      preLoaderRoute: typeof SkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water': {
      id: '/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof WaterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RailRoute: RailRoute,
  RoadRoute: RoadRoute,
  SkyRoute: SkyRoute,
  StaysRoute: StaysRoute,
  WaterRoute: WaterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
